services:
  - type: web
    name: pokeapi54-service
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start:pokemon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
  - type: web
    name: rickandmorty-api
    env: python
    rootDir: server
    buildCommand: pip install -r requirements-rick.txt
    startCommand: python -m uvicorn serverRick:app --app-dir src --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: rickandmorty
      - key: MONGODB_COLLECTION
        value: characters
      - key: ALLOWED_ORIGINS
        sync: false
  - type: web
    name: profesores-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start:profesores
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PROFESORES_MONGODB_DATABASE
        value: Profesores
      - key: ALLOWED_ORIGINS
        sync: false
